export interface ApiEndpoint {
  method: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  path: string;
  description: string;
  auth: string;
  section: string;
  body?: string;
  query?: string;
  response?: string;
  useWhen?: string;
}

export const SECTIONS = [
  'Auth & Account',
  'API Keys',
  'Search & Research',
  'Clients & Onboarding',
  'Content Pillars',
  'Knowledge Base',
  'Ideas & Content Generation',
  'Reference Videos',
  'Tasks & Todos',
  'Pipeline (Content Production)',
  'Shoots & Calendar',
  'Analyze (Video Analysis)',
  'The Nerd AI',
  'Social Media & Scheduler',
  'Reporting & Analytics',
  'Google Workspace',
  'Team & Meetings',
  'Notifications',
  'Vault',
  'Dashboard',
  'Portal Invites',
  'Settings',
  'Monday.com Integration',
  'Todoist Integration',
  'External API (v1)',
  'Cron Jobs',
] as const;

export const API_ENDPOINTS: ApiEndpoint[] = [
  // ─── 1. Auth & Account ───
  {
    method: 'POST',
    path: '/api/auth/logout',
    description: 'Sign out the current user and clear the session cookie.',
    auth: 'Required (user)',
    section: 'Auth & Account',
    response: '{ redirectTo: string }',
  },
  {
    method: 'GET',
    path: '/api/account',
    description: 'Get the current user\'s profile.',
    auth: 'Required (user)',
    section: 'Auth & Account',
    response: 'User profile object',
  },
  {
    method: 'PATCH',
    path: '/api/account',
    description: 'Update user profile fields.',
    auth: 'Required (user)',
    section: 'Auth & Account',
    body: '{ full_name?: string, avatar_url?: string, job_title?: string, password?: string }',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/account/upload-avatar',
    description: 'Upload an avatar image to storage.',
    auth: 'Required (user)',
    section: 'Auth & Account',
    body: 'FormData with file field (JPEG/PNG/WebP, max 2 MB)',
    response: '{ url: string }',
  },

  // ─── 2. API Keys ───
  {
    method: 'GET',
    path: '/api/api-keys',
    description: 'List all API keys belonging to the current user (key hashes not returned — prefix only).',
    auth: 'Required (user)',
    section: 'API Keys',
    response: '{ keys: [{ id, name, key_prefix, scopes, is_active, last_used_at, created_at, expires_at }] }',
  },
  {
    method: 'POST',
    path: '/api/api-keys',
    description: 'Create a new API key. The plaintext key is returned once only in the response.',
    auth: 'Required (user)',
    section: 'API Keys',
    body: '{ name: string, scopes: Array<\'tasks\'|\'clients\'|\'shoots\'|\'scheduler\'|\'search\'|\'team\'|\'calendar\'>, expires_at?: ISO8601 }',
    response: '{ key: { id, name, key_prefix, scopes, is_active, created_at, expires_at, plaintext } }',
  },
  {
    method: 'DELETE',
    path: '/api/api-keys/[id]',
    description: 'Revoke (deactivate) or permanently delete an API key. Only the key owner can do this.',
    auth: 'Required (user)',
    section: 'API Keys',
    query: 'permanent=true to hard-delete; omit to soft-deactivate',
    response: '{ revoked: true } or { deleted: true }',
  },

  // ─── 3. Search & Research ───
  {
    method: 'POST',
    path: '/api/search/start',
    description: 'Create a new topic research job. Returns a search ID immediately; then call /process to run the pipeline.',
    auth: 'Required (user)',
    section: 'Search & Research',
    body: '{ query: string, source?: string, time_range?: string, language?: string, country?: string, client_id?: string, search_mode?: \'general\' | \'client_strategy\' }',
    response: '{ id: string }',
    useWhen: 'Starting a new topic research from the Research Hub.',
  },
  {
    method: 'POST',
    path: '/api/search/[id]/process',
    description: 'Execute the full search pipeline: Brave SERP fetch, Claude AI analysis, store results. Long-running (up to 5 min).',
    auth: 'Required (user)',
    section: 'Search & Research',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/search/[id]',
    description: 'Retrieve a completed search result with all AI analysis data.',
    auth: 'Required (user)',
    section: 'Search & Research',
    response: 'Full TopicSearch object including summary, metrics, trending_topics, big_movers, raw_ai_response',
  },
  {
    method: 'PATCH',
    path: '/api/search/[id]',
    description: 'Approve or reject a search (marks it as reviewed/sent to client).',
    auth: 'Required (admin)',
    section: 'Search & Research',
    body: '{ action: \'approve\' | \'reject\' }',
    response: 'Updated search object',
  },
  {
    method: 'GET',
    path: '/api/search/[id]/share',
    description: 'Get the share status of a search.',
    auth: 'Required (user)',
    section: 'Search & Research',
    response: '{ shared: boolean, token?: string, url?: string }',
  },
  {
    method: 'POST',
    path: '/api/search/[id]/share',
    description: 'Create a shareable public link for a search result.',
    auth: 'Required (user)',
    section: 'Search & Research',
    response: '{ token: string, url: string, expires_at: string }',
  },
  {
    method: 'DELETE',
    path: '/api/search/[id]/share',
    description: 'Remove the shareable link for a search.',
    auth: 'Required (user)',
    section: 'Search & Research',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/search/[id]/generate-ideas',
    description: 'Generate additional video ideas for a specific topic within a completed search.',
    auth: 'Required (user)',
    section: 'Search & Research',
    body: '{ topic_name: string, existing_ideas?: string[] }',
    response: '{ ideas: VideoIdea[] }',
  },
  {
    method: 'POST',
    path: '/api/search',
    description: 'Run a synchronous topic search (legacy). Prefer the async start/process pattern instead.',
    auth: 'Required (user)',
    section: 'Search & Research',
    body: 'Same as /api/search/start',
    response: 'Full search result',
  },
  {
    method: 'GET',
    path: '/api/research/history',
    description: 'Fetch research history with optional filtering and cursor-based pagination.',
    auth: 'Required (user)',
    section: 'Search & Research',
    query: 'limit?: number, cursor?: string, type?: string, client_id?: string',
    response: '{ items: HistoryItem[], nextCursor?: string }',
  },
  {
    method: 'GET',
    path: '/api/shared/search/[token]',
    description: 'Retrieve a shared search result by token (no auth required).',
    auth: 'Public',
    section: 'Search & Research',
    response: 'Search object with client_name',
  },

  // ─── 4. Clients & Onboarding ───
  {
    method: 'GET',
    path: '/api/clients',
    description: 'List clients. Admins see all; portal viewers see only their organization\'s clients.',
    auth: 'Required (user)',
    section: 'Clients & Onboarding',
    query: 'minimal?: boolean (returns just id + name for pickers)',
    response: 'Array of client objects',
  },
  {
    method: 'POST',
    path: '/api/clients',
    description: 'Create a new client record only (no external provisioning).',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    body: '{ name, slug, industry, organization_id?, target_audience?, brand_voice?, topic_keywords?, logo_url?, website_url? }',
    response: 'Client object',
  },
  {
    method: 'GET',
    path: '/api/clients/[id]',
    description: 'Get a single client by ID.',
    auth: 'Required (user)',
    section: 'Clients & Onboarding',
    response: 'Client object',
  },
  {
    method: 'PATCH',
    path: '/api/clients/[id]',
    description: 'Update client fields.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    body: 'Any client fields to update',
    response: 'Updated client object',
  },
  {
    method: 'POST',
    path: '/api/clients/onboard',
    description: 'Full client provisioning across 4 systems in parallel: Cortex DB, Obsidian vault, Monday.com, Late social profile.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    body: '{ name, website_url, industry, target_audience?, brand_voice?, topic_keywords?, logo_url?, poc_name?, poc_email?, services?, agency? }',
    response: '{ cortex: { success, clientId, organizationId }, vault: { success }, monday: { success, mondayId }, late: { success, lateProfileId } }',
    useWhen: 'Onboarding a new client to the agency.',
  },
  {
    method: 'POST',
    path: '/api/clients/analyze-url',
    description: 'Analyze a website URL to auto-fill client profile fields during onboarding.',
    auth: 'Required (user)',
    section: 'Clients & Onboarding',
    body: '{ url: string }',
    response: '{ industry, target_audience, brand_voice, topic_keywords: string[], logo_url? }',
  },
  {
    method: 'POST',
    path: '/api/clients/upload-logo',
    description: 'Upload a client logo image (JPEG/PNG/WebP, max 2 MB) to Supabase storage.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    body: 'FormData with file field',
    response: '{ url: string }',
  },
  {
    method: 'POST',
    path: '/api/clients/preferences',
    description: 'Save or update client brand preferences (content style, topics to avoid, etc).',
    auth: 'Required (user)',
    section: 'Clients & Onboarding',
    body: '{ client_id: string, preferences: object }',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/clients/backfill-industry',
    description: 'One-time admin utility: analyze websites for all clients with industry = \'General\' and update.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    response: '{ message: string, results: [{ name, industry, status }] }',
  },
  {
    method: 'GET',
    path: '/api/clients/monday-cache',
    description: 'Fetch and cache Monday.com Clients board data (5-min in-memory cache).',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    response: 'Array of parsed Monday.com client items',
  },
  {
    method: 'GET',
    path: '/api/clients/vault/[slug]',
    description: 'Read a client\'s profile from the Obsidian vault by slug.',
    auth: 'Required (user)',
    section: 'Clients & Onboarding',
    response: 'Vault client profile object',
  },
  {
    method: 'GET',
    path: '/api/clients/assignments/strategists',
    description: 'List all clients with strategist assignments.',
    auth: 'Required (user)',
    section: 'Clients & Onboarding',
    response: '{ assignments: [{ client_id, strategist_id, strategist_name }] }',
  },
  {
    method: 'GET',
    path: '/api/clients/[id]/summary',
    description: 'Aggregated client health dashboard — team, pipeline, shoots, tasks, searches, ideas.',
    auth: 'Required (user)',
    section: 'Clients & Onboarding',
    response: '{ client, team, pipeline, upcomingShoots, taskStats, recentSearches, ideaGenerations }',
    useWhen: 'Building dashboards, AI agent context, or a client overview page.',
  },
  {
    method: 'GET',
    path: '/api/clients/[id]/strategy',
    description: 'Get the client\'s AI-generated content strategy document.',
    auth: 'Required (user)',
    section: 'Clients & Onboarding',
    response: 'Strategy object with pillars, target audience analysis, competitive positioning',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/strategy',
    description: 'Generate a new AI-powered content strategy for the client.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    response: '{ strategyId: string, status: string }',
  },
  {
    method: 'GET',
    path: '/api/clients/[id]/contacts',
    description: 'List contacts for a client.',
    auth: 'Required (user)',
    section: 'Clients & Onboarding',
    response: 'Array of contact objects',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/contacts',
    description: 'Add a contact to a client.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    body: '{ full_name: string, email?, phone?, role? }',
    response: 'Contact object',
  },
  {
    method: 'PATCH',
    path: '/api/clients/[id]/contacts/[contactId]',
    description: 'Update a contact.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    body: 'Contact fields to update',
    response: 'Updated contact',
  },
  {
    method: 'DELETE',
    path: '/api/clients/[id]/contacts/[contactId]',
    description: 'Delete a contact.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/clients/[id]/assignments',
    description: 'List team member assignments for a client.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    response: 'Array of assignment objects',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/assignments',
    description: 'Assign a team member to a client.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    body: '{ team_member_id: string, role: string, is_lead?: boolean }',
    response: 'Assignment object',
  },
  {
    method: 'DELETE',
    path: '/api/clients/[id]/assignments/[assignmentId]',
    description: 'Remove a team member assignment from a client.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/uppromote',
    description: 'Connect an UpPromote affiliate API key to a client and trigger initial sync.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    body: '{ api_key: string }',
    response: '{ success: true, message: string }',
  },
  {
    method: 'DELETE',
    path: '/api/clients/[id]/uppromote',
    description: 'Remove the UpPromote API key from a client.',
    auth: 'Required (admin)',
    section: 'Clients & Onboarding',
    response: '{ success: true }',
  },

  // ─── 5. Content Pillars ───
  {
    method: 'GET',
    path: '/api/clients/[id]/pillars',
    description: 'List all content pillars for a client, ordered by sort_order.',
    auth: 'Required (user)',
    section: 'Content Pillars',
    response: '{ pillars: ContentPillar[] }',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/pillars',
    description: 'Manually create a new content pillar.',
    auth: 'Required (user)',
    section: 'Content Pillars',
    body: '{ name, description?, emoji?, example_series?, formats?, hooks?, frequency? }',
    response: '{ pillar: ContentPillar }',
  },
  {
    method: 'PATCH',
    path: '/api/clients/[id]/pillars/[pillarId]',
    description: 'Update a content pillar\'s fields.',
    auth: 'Required (user)',
    section: 'Content Pillars',
    body: 'Any pillar fields to update',
    response: '{ pillar: ContentPillar }',
  },
  {
    method: 'DELETE',
    path: '/api/clients/[id]/pillars/[pillarId]',
    description: 'Delete a content pillar.',
    auth: 'Required (user)',
    section: 'Content Pillars',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/pillars/reorder',
    description: 'Update sort_order for a set of pillars based on the provided array order.',
    auth: 'Required (user)',
    section: 'Content Pillars',
    body: '{ pillar_ids: string[] }',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/pillars/generate',
    description: 'AI-generate new content pillars for a client. Async — returns a generation ID to poll.',
    auth: 'Required (admin)',
    section: 'Content Pillars',
    body: '{ count?: number (1-10, default 5), direction?: string }',
    response: '{ id: string, status: \'processing\' }',
  },
  {
    method: 'GET',
    path: '/api/clients/[id]/pillars/generate/[generationId]',
    description: 'Poll the status of a pillar generation job.',
    auth: 'Required (user)',
    section: 'Content Pillars',
    response: '{ generation: { id, status, count, tokens_used, estimated_cost }, pillars: ContentPillar[] | null }',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/pillars/generate-strategy',
    description: 'Full strategy pipeline: AI-generates pillars, ideas for each, then scripts — all in one background job.',
    auth: 'Required (admin)',
    section: 'Content Pillars',
    body: '{ direction?: string, pillar_count?: number (1-10), ideas_per_pillar?: number (1-10) }',
    response: '{ id: string, status: \'processing\' }',
  },
  {
    method: 'GET',
    path: '/api/clients/[id]/pillars/generate-strategy/[runId]',
    description: 'Poll the status of a full strategy pipeline run.',
    auth: 'Required (user)',
    section: 'Content Pillars',
    response: '{ run: { id, status, current_phase, error_message? } }',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/pillars/[pillarId]/reroll',
    description: 'Regenerate a single pillar using AI (delete and replace).',
    auth: 'Required (admin)',
    section: 'Content Pillars',
    response: '{ pillar: ContentPillar }',
  },

  // ─── 6. Knowledge Base ───
  {
    method: 'GET',
    path: '/api/clients/[id]/knowledge',
    description: 'List knowledge entries for a client, optionally filtered by type.',
    auth: 'Required (user)',
    section: 'Knowledge Base',
    query: 'type?: \'brand_asset\'|\'brand_profile\'|\'document\'|\'web_page\'|\'note\'|\'idea\'|\'meeting_note\'',
    response: '{ entries: KnowledgeEntry[] }',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/knowledge',
    description: 'Manually create a knowledge entry.',
    auth: 'Required (admin)',
    section: 'Knowledge Base',
    body: '{ type, title, content?, metadata?, source?: \'manual\'|\'scraped\'|\'generated\'|\'imported\' }',
    response: '{ entry: KnowledgeEntry }',
  },
  {
    method: 'PATCH',
    path: '/api/clients/[id]/knowledge/[entryId]',
    description: 'Update a knowledge entry.',
    auth: 'Required (admin)',
    section: 'Knowledge Base',
    body: 'Knowledge entry fields to update',
    response: 'Updated entry',
  },
  {
    method: 'DELETE',
    path: '/api/clients/[id]/knowledge/[entryId]',
    description: 'Delete a knowledge entry.',
    auth: 'Required (admin)',
    section: 'Knowledge Base',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/clients/[id]/knowledge/graph',
    description: 'Get the knowledge graph (entities and connections extracted from entries).',
    auth: 'Required (user)',
    section: 'Knowledge Base',
    response: '{ nodes: Entity[], edges: Connection[] }',
  },
  {
    method: 'GET',
    path: '/api/clients/[id]/knowledge/links',
    description: 'Get linked knowledge entries and relationships.',
    auth: 'Required (user)',
    section: 'Knowledge Base',
    response: 'Array of linked entry pairs',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/knowledge/brand-profile',
    description: 'Generate (or regenerate) an AI brand profile entry from all existing knowledge entries.',
    auth: 'Required (user)',
    section: 'Knowledge Base',
    response: '{ entry: KnowledgeEntry }',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/knowledge/scrape',
    description: 'Crawl the client\'s website and import pages as knowledge entries.',
    auth: 'Required (admin)',
    section: 'Knowledge Base',
    body: '{ maxPages?: number (1-100, default 50), maxDepth?: number (1-5, default 3) }',
    response: '{ message: string, count: number }',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/knowledge/import-meeting',
    description: 'Import a meeting transcript as a structured knowledge entry (extracts action items, insights).',
    auth: 'Required (user)',
    section: 'Knowledge Base',
    body: '{ transcript: string, meetingDate?: string, attendees?: string[], source?: string }',
    response: '{ entry: KnowledgeEntry, actionItems: string[], insights: string[] }',
  },
  {
    method: 'POST',
    path: '/api/clients/[id]/knowledge/generate-ideas',
    description: 'Generate video ideas from the client\'s knowledge base.',
    auth: 'Required (user)',
    section: 'Knowledge Base',
    body: '{ concept?: string, count?: number (1-50, default 10) }',
    response: '{ ideas: VideoIdea[] }',
  },
  {
    method: 'GET',
    path: '/api/knowledge/search',
    description: 'Semantic search across the knowledge base using Gemini embeddings.',
    auth: 'Required (user)',
    section: 'Knowledge Base',
    query: 'q: string, client_id?: string, limit?: number',
    response: '{ results: KnowledgeEntry[] }',
  },

  // ─── 7. Ideas & Content Generation ───
  {
    method: 'GET',
    path: '/api/ideas',
    description: 'List idea submissions, scoped by role. Admins see all; portal viewers see their client\'s ideas.',
    auth: 'Required (user)',
    section: 'Ideas & Content Generation',
    query: 'client_id?: string, status?: string',
    response: 'Array of idea submission objects',
  },
  {
    method: 'POST',
    path: '/api/ideas',
    description: 'Submit a new idea.',
    auth: 'Required (user)',
    section: 'Ideas & Content Generation',
    body: '{ client_id: string, title: string, description?, source_url?, category? }',
    response: 'Idea submission object',
  },
  {
    method: 'GET',
    path: '/api/ideas/[id]',
    description: 'Get idea generation results by generation ID.',
    auth: 'Required (user)',
    section: 'Ideas & Content Generation',
    response: 'Generation object with ideas array, status, tokens_used, estimated_cost',
  },
  {
    method: 'POST',
    path: '/api/ideas/generate',
    description: 'Generate AI-powered video ideas. Supports multiple input sources: client context, URL, search result, or pillars.',
    auth: 'Required (user)',
    section: 'Ideas & Content Generation',
    body: '{ client_id?, url?, concept?, count: number, reference_video_ids?, search_id?, pillar_ids?, ideas_per_pillar? }',
    response: '{ id: string }',
    useWhen: 'Creating video ideas from the Ideas Hub wizard.',
  },
  {
    method: 'POST',
    path: '/api/ideas/generate-script',
    description: 'Generate a spoken-word video script for a given idea using Claude AI.',
    auth: 'Required (user)',
    section: 'Ideas & Content Generation',
    body: '{ client_id, title, why_it_works?, content_pillar?, reference_video_ids?, idea_entry_id?, cta?, video_length_seconds?, target_word_count?, hook_strategies? }',
    response: '{ script: string, scriptId: string|null, usage: TokenUsage, estimatedCost: number }',
  },
  {
    method: 'POST',
    path: '/api/ideas/reject',
    description: 'Save a rejected idea to prevent it from being regenerated.',
    auth: 'Required (user)',
    section: 'Ideas & Content Generation',
    body: '{ client_id, title, description?, hook?, content_pillar?, generation_context? }',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/ideas/saved',
    description: 'List all saved ideas (type = \'idea\') from the knowledge base.',
    auth: 'Required (user)',
    section: 'Ideas & Content Generation',
    response: '{ ideas: KnowledgeEntry[] }',
  },
  {
    method: 'POST',
    path: '/api/concepts/react',
    description: 'Submit a reaction (approve/star/revision) to a concept from a search result.',
    auth: 'Required (user)',
    section: 'Ideas & Content Generation',
    body: '{ title, hook?, format?, virality?, why_it_works?, topic_name?, client_id?, search_id?, reaction, feedback? }',
    response: '{ success: true }',
  },

  // ─── 8. Reference Videos ───
  {
    method: 'GET',
    path: '/api/reference-videos',
    description: 'List reference videos, optionally filtered by client.',
    auth: 'Required (user)',
    section: 'Reference Videos',
    query: 'client_id?: string',
    response: 'Array of reference video objects (status, title, url, transcript, visual_analysis)',
  },
  {
    method: 'POST',
    path: '/api/reference-videos',
    description: 'Create a reference video record (in pending state — then call /process).',
    auth: 'Required (user)',
    section: 'Reference Videos',
    body: '{ client_id: string, url?: string, title?: string, platform?: string }',
    response: '{ video: ReferenceVideo }',
  },
  {
    method: 'POST',
    path: '/api/reference-videos/[id]/process',
    description: 'Process a reference video: transcribe with Groq and run Gemini visual analysis in parallel.',
    auth: 'Required (user)',
    section: 'Reference Videos',
    response: '{ video: ReferenceVideo } with transcript and visual_analysis populated',
  },

  // ─── 9. Tasks & Todos ───
  {
    method: 'GET',
    path: '/api/tasks',
    description: 'List tasks. Owners see all; non-owners see tasks assigned to or created by them.',
    auth: 'Required (admin)',
    section: 'Tasks & Todos',
    query: 'client_id?, assignee_id?, status?, task_type?, due_date_from?, due_date_to?',
    response: '{ tasks: Task[], is_owner: boolean, my_team_member_id: string|null, todoist_connected: boolean }',
  },
  {
    method: 'POST',
    path: '/api/tasks',
    description: 'Create a task. Auto-assigns to creator if no assignee. Pushes to Todoist if connected.',
    auth: 'Required (admin)',
    section: 'Tasks & Todos',
    body: '{ title, description?, status?, priority?, client_id?, assignee_id?, due_date?, task_type?, tags?, recurrence? }',
    response: 'Task object with client and assignee relations',
  },
  {
    method: 'PATCH',
    path: '/api/tasks/[id]',
    description: 'Update task fields. Syncs status changes to Todoist automatically.',
    auth: 'Required (admin)',
    section: 'Tasks & Todos',
    body: 'Any task fields to update',
    response: 'Updated task object',
  },
  {
    method: 'DELETE',
    path: '/api/tasks/[id]',
    description: 'Delete a task. Also deletes from Todoist if synced.',
    auth: 'Required (admin)',
    section: 'Tasks & Todos',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/tasks/search',
    description: 'Full-text search across tasks with filtering.',
    auth: 'Required (user)',
    section: 'Tasks & Todos',
    query: 'q?, status?, priority?, assignee?, client?, task_type?, due_before?, due_after?, limit?',
    response: '{ tasks: Task[], count: number }',
    useWhen: 'Finding tasks by keyword, building filtered views, AI agent task lookups.',
  },
  {
    method: 'GET',
    path: '/api/tasks/[id]/activity',
    description: 'Get the activity log and comments on a task.',
    auth: 'Required (admin)',
    section: 'Tasks & Todos',
    response: 'Array of activity entries',
  },
  {
    method: 'GET',
    path: '/api/tasks/suggestions',
    description: 'Get task suggestions aggregated from Monday.com boards.',
    auth: 'Required (admin)',
    section: 'Tasks & Todos',
    response: 'Array of suggestion objects with board_source',
  },
  {
    method: 'POST',
    path: '/api/tasks/parse',
    description: 'Parse natural language text into structured task fields using AI.',
    auth: 'Required (admin)',
    section: 'Tasks & Todos',
    body: '{ text: string }',
    response: 'Parsed task object (title, due_date, priority, assignee_name, etc)',
  },
  {
    method: 'GET',
    path: '/api/todos',
    description: 'List the current user\'s personal todos.',
    auth: 'Required (user)',
    section: 'Tasks & Todos',
    response: 'Array of todo objects',
  },
  {
    method: 'POST',
    path: '/api/todos',
    description: 'Create a personal todo.',
    auth: 'Required (user)',
    section: 'Tasks & Todos',
    body: '{ title: string, due_date?, client_id?, priority? }',
    response: 'Todo object',
  },
  {
    method: 'PATCH',
    path: '/api/todos/[id]',
    description: 'Update a todo.',
    auth: 'Required (user)',
    section: 'Tasks & Todos',
    body: 'Todo fields to update',
    response: 'Updated todo',
  },
  {
    method: 'DELETE',
    path: '/api/todos/[id]',
    description: 'Delete a todo.',
    auth: 'Required (user)',
    section: 'Tasks & Todos',
    response: '{ success: true }',
  },

  // ─── 10. Pipeline (Content Production) ───
  {
    method: 'GET',
    path: '/api/pipeline',
    description: 'List pipeline items for a given month.',
    auth: 'Required (user)',
    section: 'Pipeline (Content Production)',
    query: 'month: string (YYYY-MM-DD format, first day of month)',
    response: '{ items: PipelineItem[] }',
  },
  {
    method: 'POST',
    path: '/api/pipeline',
    description: 'Add a client to the pipeline for a month.',
    auth: 'Required (admin)',
    section: 'Pipeline (Content Production)',
    body: '{ client_name, month_label, month_date, agency? }',
    response: 'Pipeline item',
  },
  {
    method: 'PATCH',
    path: '/api/pipeline/[id]',
    description: 'Update any pipeline item field (status, team, dates, links, notes).',
    auth: 'Required (admin)',
    section: 'Pipeline (Content Production)',
    body: '{ [field]: value }',
    response: 'Updated item',
  },
  {
    method: 'DELETE',
    path: '/api/pipeline/[id]',
    description: 'Remove a client from the pipeline month.',
    auth: 'Required (admin)',
    section: 'Pipeline (Content Production)',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/pipeline/[id]/advance',
    description: 'Smart status advancement with transition validation. Advances a specific production track.',
    auth: 'Required (user)',
    section: 'Pipeline (Content Production)',
    body: '{ track: \'assignment\'|\'raws\'|\'editing\'|\'client_approval\'|\'boosting\', target_status?: string }',
    response: '{ item: PipelineItem, transition: { track, from, to } }',
    useWhen: 'An editor marks work done, a manager approves, or any pipeline status needs to advance.',
  },
  {
    method: 'GET',
    path: '/api/pipeline/summary',
    description: 'Get pipeline summary statistics and health metrics.',
    auth: 'Required (user)',
    section: 'Pipeline (Content Production)',
    response: 'Summary stats object with counts by status',
  },
  {
    method: 'POST',
    path: '/api/pipeline/sync',
    description: 'Sync pipeline items from Monday.com Content Calendars board.',
    auth: 'Required (admin)',
    section: 'Pipeline (Content Production)',
    body: '{ api_token?, group_id? }',
    response: '{ synced: number, errors?: string[] }',
  },

  // ─── 11. Shoots & Calendar ───
  {
    method: 'GET',
    path: '/api/shoots',
    description: 'List shoot events with optional filtering.',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    query: 'client_id?, status?, date_from? (YYYY-MM-DD), date_to? (YYYY-MM-DD)',
    response: 'Array of shoot events with client relation',
  },
  {
    method: 'GET',
    path: '/api/shoots/[id]',
    description: 'Get a single shoot event by ID.',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    response: 'Shoot event with client relation',
  },
  {
    method: 'PATCH',
    path: '/api/shoots/[id]',
    description: 'Update a shoot event\'s fields (title, date, location, status, notes).',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    body: '{ title?, client_id?, shoot_date?, location?, notes?, scheduled_status? }',
    response: 'Updated shoot event',
  },
  {
    method: 'DELETE',
    path: '/api/shoots/[id]',
    description: 'Delete a shoot event.',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/shoots/schedule',
    description: 'Schedule a shoot: creates a shoot event, optionally creates a Google Calendar event, sends email invites.',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    body: '{ client_name, client_id, shoot_date, shoot_time?, location?, notes?, agency, team_emails, client_emails, videographer_emails, add_to_calendar, send_invites }',
    response: '{ success: true, shootId, googleEventCreated, invitesSent }',
  },
  {
    method: 'POST',
    path: '/api/shoots/reschedule',
    description: 'Update the shoot date on the Monday.com Content Calendars board.',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    body: '{ monday_item_id: string, new_date: string (YYYY-MM-DD) }',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/shoots/ideate',
    description: 'Generate an AI-powered shoot plan (video ideas, equipment, talking points) for a client.',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    body: '{ clientName, clientId?, shootDate?, industry?, context }',
    response: '{ plan: ShootPlan, usage, estimatedCost }',
  },
  {
    method: 'POST',
    path: '/api/shoots/[id]/plan',
    description: 'Generate a full AI shoot plan for an existing shoot event. Pulls live SERP data + client content memory.',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    response: '{ shootId, status: \'generated\', plan: ShootPlan }',
  },
  {
    method: 'PATCH',
    path: '/api/shoots/[id]/footage',
    description: 'Update raw footage upload status for a shoot.',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    body: '{ raw_footage_uploaded: boolean, raw_footage_url?: string }',
    response: 'Updated shoot event',
  },
  {
    method: 'POST',
    path: '/api/shoots/sync',
    description: 'Sync upcoming Google Calendar events via Nango, filter for shoot events, upsert into shoot_events.',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    response: '{ synced: number }',
  },
  {
    method: 'GET',
    path: '/api/shoots/content-calendar',
    description: 'Fetch shoot data from Monday.com Content Calendars board (cached 10 min).',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    response: 'Array of parsed shoot items',
  },
  {
    method: 'GET',
    path: '/api/calendar/events',
    description: 'Fetch Google Calendar events for the current user via Nango (2-min cache).',
    auth: 'Required (user)',
    section: 'Shoots & Calendar',
    query: 'days_ahead?: number, calendars?: comma-separated calendar IDs',
    response: '[{ name, color, connection_type, events: CalendarEvent[] }]',
  },
  {
    method: 'POST',
    path: '/api/calendar/sync',
    description: 'Pull Google Calendar events and identify + import shoot events into the shoot_events table.',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    response: '{ imported: number, matched: number }',
  },
  {
    method: 'POST',
    path: '/api/calendar/invite',
    description: 'Generate a calendar connection invite token for a contact.',
    auth: 'Required (admin)',
    section: 'Shoots & Calendar',
    body: '{ contact_id: string }',
    response: '{ token, url }',
  },
  {
    method: 'GET',
    path: '/api/calendar/connect/[token]',
    description: 'Accept a calendar connection invite via token.',
    auth: 'Public',
    section: 'Shoots & Calendar',
    response: 'Redirects to connect flow',
  },
  {
    method: 'GET',
    path: '/api/calendar/gaps',
    description: 'Find free time slots in connected calendars.',
    auth: 'Required (user)',
    section: 'Shoots & Calendar',
    query: 'date_from, date_to, min_duration?',
    response: 'Array of free time slot objects',
  },
  {
    method: 'POST',
    path: '/api/calendar/webhook',
    description: 'Receive Google Calendar push notification webhooks.',
    auth: 'Public (webhook)',
    section: 'Shoots & Calendar',
    response: '{ ok: true }',
  },

  // ─── 12. Analyze (Video Analysis) ───
  {
    method: 'GET',
    path: '/api/moodboard/boards',
    description: 'List all analysis boards.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'Array of board objects with item count',
  },
  {
    method: 'POST',
    path: '/api/moodboard/boards',
    description: 'Create a new analysis board.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: '{ name, description?, client_id?, template_id? }',
    response: 'New board object',
  },
  {
    method: 'GET',
    path: '/api/moodboard/boards/[id]',
    description: 'Get a board with all items, notes, edges, and tags.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'Full board object',
  },
  {
    method: 'PATCH',
    path: '/api/moodboard/boards/[id]',
    description: 'Update a board\'s name, description, or client association.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: 'Board fields to update',
    response: 'Updated board',
  },
  {
    method: 'DELETE',
    path: '/api/moodboard/boards/[id]',
    description: 'Delete a board and all its items.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/moodboard/boards/[id]/share',
    description: 'Create a shareable link with optional password and expiry.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: '{ password?, expires_days? }',
    response: '{ token, url, expires_at }',
  },
  {
    method: 'POST',
    path: '/api/moodboard/boards/[id]/duplicate',
    description: 'Duplicate a board with all items.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'New board object',
  },
  {
    method: 'GET',
    path: '/api/moodboard/boards/[id]/search',
    description: 'Full-text search items within a board.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    query: 'q: string',
    response: '{ item_ids: string[] }',
  },
  {
    method: 'PATCH',
    path: '/api/moodboard/boards/[id]/positions',
    description: 'Batch-update canvas positions of items and notes within a board.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: '{ items?: [{ id, position_x, position_y, width?, height? }], notes?: [...] }',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/moodboard/boards/[id]/tags',
    description: 'Get tags on a board.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'Array of tag objects',
  },
  {
    method: 'PATCH',
    path: '/api/moodboard/boards/[id]/tags',
    description: 'Manage tags on a board.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: 'Tag management payload',
    response: 'Updated tags',
  },
  {
    method: 'GET',
    path: '/api/moodboard/items',
    description: 'List items, optionally filtered by board.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    query: 'board_id?: string',
    response: 'Array of analysis items',
  },
  {
    method: 'POST',
    path: '/api/moodboard/items',
    description: 'Create a new item (video or website). For TikTok URLs, auto-fetches metadata.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: '{ board_id, type: \'video\'|\'website\'|\'image\', url?, title? }',
    response: 'Created item object',
  },
  {
    method: 'GET',
    path: '/api/moodboard/items/[id]',
    description: 'Get a single analysis item.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'Item object',
  },
  {
    method: 'PATCH',
    path: '/api/moodboard/items/[id]',
    description: 'Update item fields.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: 'Item fields to update',
    response: 'Updated item',
  },
  {
    method: 'DELETE',
    path: '/api/moodboard/items/[id]',
    description: 'Delete an analysis board item.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/moodboard/items/[id]/process',
    description: 'Full video processing pipeline: download, extract frames, transcribe, generate AI analysis.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ item: AnalyzeItem } with transcript, visual_analysis, and concept_summary populated',
  },
  {
    method: 'POST',
    path: '/api/moodboard/items/[id]/reprocess',
    description: 'Re-run the full video processing pipeline (overwriting existing results).',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ item: AnalyzeItem }',
  },
  {
    method: 'POST',
    path: '/api/moodboard/items/[id]/analyze',
    description: 'Run AI analysis on an item (visual breakdown, hook analysis, engagement patterns).',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ analysis: object }',
  },
  {
    method: 'POST',
    path: '/api/moodboard/items/[id]/insights',
    description: 'Generate or regenerate AI creative insights for an item.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ insights: object }',
  },
  {
    method: 'POST',
    path: '/api/moodboard/items/[id]/transcribe',
    description: 'Transcribe the audio of a video item.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ transcript: string }',
  },
  {
    method: 'POST',
    path: '/api/moodboard/items/[id]/extract-frames',
    description: 'Extract frame thumbnails from a video item using ffmpeg.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ frames: string[] }',
  },
  {
    method: 'GET',
    path: '/api/moodboard/items/[id]/thumbnail',
    description: 'Get (or generate) a thumbnail for an item.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ thumbnail_url: string }',
  },
  {
    method: 'GET',
    path: '/api/moodboard/items/[id]/video-url',
    description: 'Get a pre-signed or proxied URL for streaming a video item.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ url: string }',
  },
  {
    method: 'POST',
    path: '/api/moodboard/items/[id]/rescript',
    description: 'Generate a new script adapted from a video item\'s transcript for a specific brand.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: '{ client_id?, brand_voice?, product?, target_audience?, notes? }',
    response: '{ script: string, usage, estimatedCost }',
  },
  {
    method: 'POST',
    path: '/api/moodboard/items/[id]/replicate',
    description: 'Generate a content strategy for replicating a video item\'s style.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: '{ client_id?, format: string, notes? }',
    response: '{ strategy: string, usage, estimatedCost }',
  },
  {
    method: 'GET',
    path: '/api/moodboard/items/[id]/tags',
    description: 'Get tags on an analysis board item.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'Array of tag objects',
  },
  {
    method: 'POST',
    path: '/api/moodboard/items/[id]/tags',
    description: 'Add tags to an analysis board item.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: '{ tag_ids: string[] }',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/moodboard/items/batch-tags',
    description: 'Apply tags to multiple items at once.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: '{ item_ids: string[], tag_ids: string[] }',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/moodboard/items/[id]/analysis/pdf',
    description: 'Generate and stream a PDF analysis report for an item.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'PDF file stream',
  },
  {
    method: 'GET',
    path: '/api/moodboard/items/[id]/brief/pdf',
    description: 'Generate and stream a PDF creative brief for an item.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'PDF file stream',
  },
  {
    method: 'POST',
    path: '/api/moodboard/chat',
    description: 'AI chat (Cortex AI) with analysis item context. Returns SSE stream.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: '{ board_id, item_ids: string[], messages: [{role, content}], note_contents?, client_slugs?, model? }',
    response: 'Server-sent events stream (text/event-stream)',
    useWhen: 'Analyzing video hooks, comparing content styles, drafting new scripts inspired by board items.',
  },
  {
    method: 'GET',
    path: '/api/moodboard/notes',
    description: 'List sticky notes on a board.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'Array of note objects',
  },
  {
    method: 'POST',
    path: '/api/moodboard/notes',
    description: 'Create a sticky note on a board.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: '{ board_id, content?, color?, position_x?, position_y? }',
    response: 'Note object',
  },
  {
    method: 'PATCH',
    path: '/api/moodboard/notes/[id]',
    description: 'Update a sticky note.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: 'Note fields to update',
    response: 'Updated note',
  },
  {
    method: 'DELETE',
    path: '/api/moodboard/notes/[id]',
    description: 'Delete a sticky note.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/moodboard/edges',
    description: 'List connection edges between items on a board.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'Array of edge objects',
  },
  {
    method: 'POST',
    path: '/api/moodboard/edges',
    description: 'Create a connection edge between items on a board.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: 'Edge definition',
    response: 'Edge object',
  },
  {
    method: 'PATCH',
    path: '/api/moodboard/edges/[id]',
    description: 'Update an edge.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: 'Edge fields to update',
    response: 'Updated edge',
  },
  {
    method: 'DELETE',
    path: '/api/moodboard/edges/[id]',
    description: 'Delete an edge.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/moodboard/comments',
    description: 'List comments on board items.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'Array of comment objects',
  },
  {
    method: 'POST',
    path: '/api/moodboard/comments',
    description: 'Create a comment on a board item.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: 'Comment content',
    response: 'Comment object',
  },
  {
    method: 'PATCH',
    path: '/api/moodboard/comments/[id]',
    description: 'Update a comment.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'Updated comment',
  },
  {
    method: 'DELETE',
    path: '/api/moodboard/comments/[id]',
    description: 'Delete a comment.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ success: true }',
  },
  {
    method: 'PATCH',
    path: '/api/moodboard/tags/[id]',
    description: 'Update a tag definition.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    body: 'Tag fields to update',
    response: 'Updated tag',
  },
  {
    method: 'DELETE',
    path: '/api/moodboard/tags/[id]',
    description: 'Delete a tag definition.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/moodboard/templates',
    description: 'List available board templates.',
    auth: 'Required (admin)',
    section: 'Analyze (Video Analysis)',
    response: 'Array of template objects',
  },
  {
    method: 'GET',
    path: '/api/shared/moodboard/[token]',
    description: 'Public access to a shared analysis board (supports optional password).',
    auth: 'Public',
    section: 'Analyze (Video Analysis)',
    query: 'password?: string',
    response: 'Board with items (password-protected if configured)',
  },

  // ─── 13. The Nerd AI ───
  {
    method: 'POST',
    path: '/api/nerd/chat',
    description: 'The Nerd AI assistant — a tool-calling Claude agent with full access to client data. Returns SSE stream.',
    auth: 'Required (user)',
    section: 'The Nerd AI',
    body: '{ messages: [{role, content, tool_call_id?}], mentions?: [{type, id, name, slug?}], actionConfirmation?: { toolName, arguments, confirmed } }',
    response: 'Server-sent events stream (text/event-stream)',
    useWhen: 'Asking strategic questions, generating ideas, creating tasks, looking up client info.',
  },
  {
    method: 'GET',
    path: '/api/nerd/clients',
    description: 'List all active clients for @mention autocomplete in The Nerd.',
    auth: 'Required (user)',
    section: 'The Nerd AI',
    response: 'Array of { name, slug, agency }',
  },
  {
    method: 'GET',
    path: '/api/nerd/mentions',
    description: 'Fetch all clients and team members for @mention autocomplete in The Nerd.',
    auth: 'Required (user)',
    section: 'The Nerd AI',
    response: '{ clients: [{type, id, name, slug, agency, avatarUrl}], team: [{type, id, name, role, avatarUrl}] }',
  },

  // ─── 14. Social Media & Scheduler ───
  {
    method: 'GET',
    path: '/api/scheduler/posts',
    description: 'List scheduled posts for a client, with optional status filter.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    query: 'client_id: string (required), status?: \'draft\'|\'scheduled\'|\'published\'|\'failed\'',
    response: 'Array of scheduled post objects',
  },
  {
    method: 'POST',
    path: '/api/scheduler/posts',
    description: 'Create a new scheduled post (draft or scheduled).',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: '{ client_id, caption?, hashtags?, scheduled_at?, status?, platform_profile_ids?, media_ids?, cover_image_url?, tagged_people?, collaborator_handles? }',
    response: 'Created post object',
  },
  {
    method: 'PUT',
    path: '/api/scheduler/posts/[id]',
    description: 'Update a scheduled post.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: 'Post fields to update',
    response: 'Updated post object',
  },
  {
    method: 'DELETE',
    path: '/api/scheduler/posts/[id]',
    description: 'Delete a scheduled post.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/scheduler/posts/batch-publish',
    description: 'Immediately publish a batch of scheduled posts to their social platforms.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: '{ posts: string[] }',
    response: '{ published: number, errors?: string[] }',
  },
  {
    method: 'POST',
    path: '/api/scheduler/posts/publish-drafts',
    description: 'Publish all posts with status = \'scheduled\' whose scheduled_at is in the past.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    response: '{ published: number }',
  },
  {
    method: 'POST',
    path: '/api/scheduler/auto-schedule',
    description: 'Bulk AI caption generation + scheduling. Distributes media across a date range with AI captions.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: '{ client_id, start_date, end_date, posts_per_week, posting_time, platform_profile_ids, media_ids? }',
    response: '{ scheduled: number, posts: ScheduledPost[] }',
  },
  {
    method: 'GET',
    path: '/api/scheduler/profiles',
    description: 'List connected social profiles (Late accounts) for a client.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    query: 'client_id: string (required)',
    response: '{ profiles: [{ id, platform, username, avatar_url, late_account_id }] }',
  },
  {
    method: 'POST',
    path: '/api/scheduler/connect',
    description: 'Start the OAuth flow to connect a social platform account for a client via Late.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: '{ platform: \'facebook\'|\'instagram\'|\'tiktok\'|\'youtube\', client_id: string }',
    response: '{ authUrl: string }',
  },
  {
    method: 'GET',
    path: '/api/scheduler/connect/callback',
    description: 'OAuth callback handler after social platform authorization.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    query: 'client_id, platform, code, state',
    response: 'Redirects to scheduler settings page',
  },
  {
    method: 'GET',
    path: '/api/scheduler/analytics',
    description: 'Fetch post analytics from Late for a client\'s connected social accounts.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    query: 'client_id, start (YYYY-MM-DD), end (YYYY-MM-DD)',
    response: '{ analytics: [{ platform, ...metrics }] }',
  },
  {
    method: 'POST',
    path: '/api/scheduler/media',
    description: 'Get a presigned upload URL or confirm a completed media upload.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: '{ action: \'get-upload-url\'|\'confirm-upload\', ... }',
    response: '{ uploadUrl, publicUrl } or Media record object',
  },
  {
    method: 'GET',
    path: '/api/scheduler/media',
    description: 'List uploaded media for a client.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    query: 'client_id: string, is_used?: boolean',
    response: 'Array of media objects',
  },
  {
    method: 'DELETE',
    path: '/api/scheduler/media/[id]',
    description: 'Delete a media item.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/scheduler/ai/hashtag-suggestions',
    description: 'Generate AI hashtag suggestions for a caption.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: '{ text: string, platform?: string }',
    response: '{ hashtags: string[] }',
  },
  {
    method: 'POST',
    path: '/api/scheduler/ai/improve-caption',
    description: 'Use AI to improve/rewrite an existing caption with client brand context.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: '{ caption: string, client_id?: string }',
    response: '{ improved_caption: string }',
  },
  {
    method: 'GET',
    path: '/api/scheduler/review',
    description: 'Get post review records for a client.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    query: 'client_id: string',
    response: 'Array of review objects',
  },
  {
    method: 'POST',
    path: '/api/scheduler/review',
    description: 'Create a review record for a post.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: '{ post_id: string, status: string, notes? }',
    response: 'Review object',
  },
  {
    method: 'POST',
    path: '/api/scheduler/review/comment',
    description: 'Add a comment to a post review.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: '{ review_id: string, content: string }',
    response: 'Comment object',
  },
  {
    method: 'GET',
    path: '/api/scheduler/saved-captions',
    description: 'List saved caption templates for a client.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    query: 'client_id: string',
    response: 'Array of saved caption objects',
  },
  {
    method: 'POST',
    path: '/api/scheduler/saved-captions',
    description: 'Save a reusable caption template.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: '{ client_id, title, caption_text, hashtags? }',
    response: 'Saved caption object',
  },
  {
    method: 'POST',
    path: '/api/scheduler/share',
    description: 'Create a shareable calendar review link for selected posts.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    body: '{ client_id, post_ids: string[], label?: string }',
    response: '{ link: object, url: string }',
  },
  {
    method: 'POST',
    path: '/api/scheduler/share/feedback',
    description: 'Submit client feedback on a shared calendar review link.',
    auth: 'Public',
    section: 'Social Media & Scheduler',
    body: '{ token, post_id, feedback, status }',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/scheduler/webhooks',
    description: 'Receive posting status webhooks from Late.',
    auth: 'Public (webhook)',
    section: 'Social Media & Scheduler',
    response: '{ ok: true }',
  },
  {
    method: 'GET',
    path: '/api/social/profiles',
    description: 'List active social profiles for a client.',
    auth: 'Required (user)',
    section: 'Social Media & Scheduler',
    query: 'clientId: string (required)',
    response: 'Array of social profile objects',
  },
  {
    method: 'GET',
    path: '/api/social/connect/[platform]',
    description: 'Start OAuth flow for connecting a social account directly.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
  },
  {
    method: 'GET',
    path: '/api/social/callback/[platform]',
    description: 'Handle OAuth callback for social platform connection.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
  },
  {
    method: 'DELETE',
    path: '/api/social/disconnect/[profileId]',
    description: 'Disconnect a social profile.',
    auth: 'Required (admin)',
    section: 'Social Media & Scheduler',
    response: '{ success: true }',
  },

  // ─── 15. Reporting & Analytics ───
  {
    method: 'GET',
    path: '/api/reporting/summary',
    description: 'Generate analytics summary for a client over a date range.',
    auth: 'Required (user)',
    section: 'Reporting & Analytics',
    query: 'clientId, start (YYYY-MM-DD), end (YYYY-MM-DD)',
    response: '{ combined, platforms, dateRange }',
  },
  {
    method: 'GET',
    path: '/api/reporting/top-posts',
    description: 'Get top-performing posts for a client sorted by engagement.',
    auth: 'Required (user)',
    section: 'Reporting & Analytics',
    query: 'client_id, limit?, platform?',
    response: 'Array of top posts with metrics',
  },
  {
    method: 'POST',
    path: '/api/reporting/sync',
    description: 'Sync social analytics data from Meta/Instagram for a client.',
    auth: 'Required (user)',
    section: 'Reporting & Analytics',
    body: '{ clientId, dateRange?: { start, end } }',
    response: '{ synced: number }',
  },
  {
    method: 'POST',
    path: '/api/reporting/share',
    description: 'Create a shareable analytics report link.',
    auth: 'Required (admin)',
    section: 'Reporting & Analytics',
    body: '{ client_id, date_from, date_to }',
    response: '{ token, url, expires_at }',
  },
  {
    method: 'GET',
    path: '/api/reporting/shared/[token]',
    description: 'Public access to a shared analytics report.',
    auth: 'Public',
    section: 'Reporting & Analytics',
    response: 'Report data',
  },
  {
    method: 'GET',
    path: '/api/instagram/accounts',
    description: 'List connected Instagram accounts.',
    auth: 'Required (admin)',
    section: 'Reporting & Analytics',
    response: 'Array of Instagram account objects',
  },
  {
    method: 'GET',
    path: '/api/instagram/media',
    description: 'Get recent Instagram media with optional insights.',
    auth: 'Required (admin)',
    section: 'Reporting & Analytics',
    query: 'account_id, limit?, insights?',
    response: 'Array of media objects with engagement data',
  },
  {
    method: 'GET',
    path: '/api/instagram/insights',
    description: 'Get account-level Instagram insights (reach, impressions, followers).',
    auth: 'Required (admin)',
    section: 'Reporting & Analytics',
    query: 'account_id, period?',
    response: 'Insights object',
  },
  {
    method: 'GET',
    path: '/api/instagram/demographics',
    description: 'Get Instagram audience demographic data.',
    auth: 'Required (admin)',
    section: 'Reporting & Analytics',
    query: 'account_id',
    response: 'Demographics object',
  },
  {
    method: 'GET',
    path: '/api/analytics/meta',
    description: 'Fetch Meta Ads Manager data: campaigns, ad sets, and ads with insights.',
    auth: 'Required (admin)',
    section: 'Reporting & Analytics',
    query: 'datePreset: \'last_7d\'|\'last_14d\'|\'last_30d\'|\'this_month\'|\'all_time\'|\'custom\', dateFrom?, dateTo?',
    response: 'Structured campaigns and performance data',
  },
  {
    method: 'GET',
    path: '/api/affiliates',
    description: 'Get UpPromote affiliate analytics for a client.',
    auth: 'Required (admin)',
    section: 'Reporting & Analytics',
    query: 'clientId, start (YYYY-MM-DD), end (YYYY-MM-DD)',
    response: 'Affiliate stats (affiliates, referrals, sales, commissions, clicks, top affiliates)',
  },

  // ─── 16. Google Workspace ───
  {
    method: 'GET',
    path: '/api/google',
    description: 'Get the current user\'s Google Workspace connection status.',
    auth: 'Required (user)',
    section: 'Google Workspace',
    response: '{ connected: boolean, email?, scopes? }',
  },
  {
    method: 'GET',
    path: '/api/google/status',
    description: 'Detailed status of Google connection including which services are available.',
    auth: 'Required (user)',
    section: 'Google Workspace',
    response: '{ calendar: boolean, drive: boolean, chat: boolean, gmail: boolean }',
  },
  {
    method: 'GET',
    path: '/api/google/callback',
    description: 'OAuth callback from Google for workspace connection.',
    auth: 'Required (user)',
    section: 'Google Workspace',
    response: 'Redirects to settings page',
  },
  {
    method: 'POST',
    path: '/api/google/disconnect',
    description: 'Disconnect Google Workspace from the current user\'s account.',
    auth: 'Required (user)',
    section: 'Google Workspace',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/google/chat',
    description: 'List Google Chat spaces, or list messages in a specific space.',
    auth: 'Required (user)',
    section: 'Google Workspace',
    query: 'space?: string (spaces/xxx format), pageToken?',
    response: '{ spaces: [...] } or { messages: [...], nextPageToken? }',
  },
  {
    method: 'GET',
    path: '/api/google/drive',
    description: 'List files from Google Drive.',
    auth: 'Required (user)',
    section: 'Google Workspace',
    query: 'folderId?, q? (search query), pageToken?, pageSize?',
    response: '{ files: [...], nextPageToken? }',
  },
  {
    method: 'GET',
    path: '/api/nango/connect',
    description: 'Initiate Nango OAuth connection for Google Calendar.',
    auth: 'Required (user)',
    section: 'Google Workspace',
    response: 'Redirect URL',
  },
  {
    method: 'GET',
    path: '/api/nango/callback',
    description: 'Nango OAuth callback handler.',
    auth: 'Required (user)',
    section: 'Google Workspace',
    response: 'Redirects to settings page',
  },

  // ─── 17. Team & Meetings ───
  {
    method: 'GET',
    path: '/api/team',
    description: 'List all active team members.',
    auth: 'Required (admin)',
    section: 'Team & Meetings',
    response: 'Array of team member objects (id, full_name, email, role, avatar_url, is_active)',
  },
  {
    method: 'POST',
    path: '/api/team',
    description: 'Create a new team member record.',
    auth: 'Required (admin)',
    section: 'Team & Meetings',
    body: '{ full_name: string, email?, role?, avatar_url? }',
    response: 'Team member object',
  },
  {
    method: 'PATCH',
    path: '/api/team/[id]',
    description: 'Update a team member\'s profile.',
    auth: 'Required (admin)',
    section: 'Team & Meetings',
    body: 'Team member fields to update',
    response: 'Updated team member',
  },
  {
    method: 'DELETE',
    path: '/api/team/[id]',
    description: 'Deactivate a team member (soft delete).',
    auth: 'Required (admin)',
    section: 'Team & Meetings',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/team/[id]/workload',
    description: 'Get a team member\'s current workload — client assignments, open/overdue tasks, pipeline items.',
    auth: 'Required (user)',
    section: 'Team & Meetings',
    response: '{ member, assignments, tasks: { open, overdue, items }, pipeline: { count, items } }',
    useWhen: 'Checking capacity before assigning work, building team dashboards.',
  },
  {
    method: 'POST',
    path: '/api/team/[id]/invite',
    description: 'Generate an invite link for a team member to create their Cortex account.',
    auth: 'Required (admin)',
    section: 'Team & Meetings',
    response: '{ invite_url, expires_at }',
  },
  {
    method: 'POST',
    path: '/api/team/[id]/link',
    description: 'Link a team member record to an existing auth user account.',
    auth: 'Required (admin)',
    section: 'Team & Meetings',
    body: '{ user_id: string }',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/team/linkable-users',
    description: 'List auth users that are not yet linked to a team member.',
    auth: 'Required (admin)',
    section: 'Team & Meetings',
    response: 'Array of linkable user objects',
  },
  {
    method: 'GET',
    path: '/api/team/invite/validate',
    description: 'Validate a team invite token (check expiry and usage).',
    auth: 'Public',
    section: 'Team & Meetings',
    query: 'token: string',
    response: '{ valid: true, email, member_name, member_role } or error',
  },
  {
    method: 'POST',
    path: '/api/team/invite/accept',
    description: 'Accept a team invite and create the user\'s Cortex account.',
    auth: 'Public',
    section: 'Team & Meetings',
    body: '{ token, full_name, email, password }',
    response: '{ success: true, user_id }',
  },
  {
    method: 'GET',
    path: '/api/meetings',
    description: 'List meetings with attendees.',
    auth: 'Required (user)',
    section: 'Team & Meetings',
    response: 'Array of meeting objects',
  },
  {
    method: 'POST',
    path: '/api/meetings',
    description: 'Create a meeting record.',
    auth: 'Required (user)',
    section: 'Team & Meetings',
    body: '{ title, attendees?, date, duration?, notes?, recurrence? }',
    response: 'Meeting object',
  },
  {
    method: 'PATCH',
    path: '/api/meetings/[id]',
    description: 'Update a meeting.',
    auth: 'Required (user)',
    section: 'Team & Meetings',
    body: 'Meeting fields to update',
    response: 'Updated meeting',
  },
  {
    method: 'DELETE',
    path: '/api/meetings/[id]',
    description: 'Delete a meeting.',
    auth: 'Required (user)',
    section: 'Team & Meetings',
    response: '{ success: true }',
  },

  // ─── 18. Notifications ───
  {
    method: 'GET',
    path: '/api/notifications',
    description: 'List notifications for the authenticated user.',
    auth: 'Required (user)',
    section: 'Notifications',
    query: 'unread_only?: boolean, limit?: number',
    response: '{ notifications: Notification[], unread_count: number }',
  },
  {
    method: 'PATCH',
    path: '/api/notifications/[id]',
    description: 'Mark a notification as read.',
    auth: 'Required (user)',
    section: 'Notifications',
    body: '{ read: true }',
    response: 'Updated notification',
  },
  {
    method: 'POST',
    path: '/api/notifications/mark-all-read',
    description: 'Mark all of the current user\'s notifications as read.',
    auth: 'Required (user)',
    section: 'Notifications',
    response: '{ updated: number }',
  },
  {
    method: 'GET',
    path: '/api/notifications/preferences',
    description: 'Get the current user\'s notification preferences.',
    auth: 'Required (user)',
    section: 'Notifications',
    response: 'Preferences object',
  },
  {
    method: 'PATCH',
    path: '/api/notifications/preferences',
    description: 'Update notification preferences.',
    auth: 'Required (user)',
    section: 'Notifications',
    body: 'Preferences fields to update',
    response: 'Updated preferences',
  },

  // ─── 19. Vault ───
  {
    method: 'GET',
    path: '/api/vault/search',
    description: 'Search the Obsidian vault using full-text or semantic search.',
    auth: 'Required (user)',
    section: 'Vault',
    query: 'q: string, limit?: number, mode?: \'fts\'|\'semantic\'',
    response: '{ query, mode, count, results: [{ path, title, excerpt, score }] }',
  },
  {
    method: 'POST',
    path: '/api/vault/init',
    description: 'Initialize the vault with templates and client profile stubs.',
    auth: 'Required (admin)',
    section: 'Vault',
    response: '{ initialized: true }',
  },
  {
    method: 'POST',
    path: '/api/vault/provision',
    description: 'Read vault client profiles and provision/update them in the Cortex database.',
    auth: 'Required (admin)',
    section: 'Vault',
    response: '{ provisioned: number }',
  },
  {
    method: 'POST',
    path: '/api/vault/index',
    description: 'Re-index all vault files for semantic search.',
    auth: 'Required (admin)',
    section: 'Vault',
    response: '{ indexed: number }',
  },
  {
    method: 'GET',
    path: '/api/vault/[...path]',
    description: 'Read a file from the vault (proxied to GitHub API).',
    auth: 'Required (admin)',
    section: 'Vault',
    response: 'File content (JSON or text)',
  },
  {
    method: 'PUT',
    path: '/api/vault/[...path]',
    description: 'Write a file to the vault (proxied to GitHub API).',
    auth: 'Required (admin)',
    section: 'Vault',
    body: '{ content: string, message?: string }',
    response: 'Commit info',
  },
  {
    method: 'POST',
    path: '/api/vault/webhook',
    description: 'GitHub push webhook receiver. Re-indexes changed markdown files. Validates HMAC signature.',
    auth: 'Public (webhook)',
    section: 'Vault',
    response: '{ indexed: number }',
  },

  // ─── 20. Dashboard ───
  {
    method: 'GET',
    path: '/api/dashboard/stats',
    description: 'Get dashboard widget statistics (basic counts).',
    auth: 'Required (user)',
    section: 'Dashboard',
    response: 'Stats object',
  },
  {
    method: 'GET',
    path: '/api/dashboard/overview',
    description: 'Comprehensive agency pulse — active clients, pipeline, tasks, shoots, notifications, searches.',
    auth: 'Required (user)',
    section: 'Dashboard',
    response: '{ clients, pipeline, tasks, upcomingShoots, unreadNotifications, recentSearches }',
    useWhen: 'Building dashboard views, AI agent status checks, quick operational overview.',
  },
  {
    method: 'GET',
    path: '/api/activity',
    description: 'Fetch recent activity log entries. Admins see all; portal viewers see only their org\'s activity.',
    auth: 'Required (user)',
    section: 'Dashboard',
    query: 'limit?: number (max 100, default 50)',
    response: 'Array of activity log entries (most recent first)',
  },
  {
    method: 'GET',
    path: '/api/usage',
    description: 'Get AI usage and cost summary for a time period.',
    auth: 'Required (user)',
    section: 'Dashboard',
    query: 'from?: ISO8601, to?: ISO8601 (default: last 30 days)',
    response: 'Usage summary with costs by feature and model',
  },

  // ─── 21. Portal Invites ───
  {
    method: 'POST',
    path: '/api/invites',
    description: 'Generate a portal invite token for a client organization.',
    auth: 'Required (admin)',
    section: 'Portal Invites',
    body: '{ client_id: string }',
    response: '{ token, invite_url, expires_at, client_name }',
  },
  {
    method: 'GET',
    path: '/api/invites/validate',
    description: 'Check if a portal invite token is valid and not expired.',
    auth: 'Public',
    section: 'Portal Invites',
    query: 'token: string',
    response: '{ valid: true, client_name } or error',
  },
  {
    method: 'POST',
    path: '/api/invites/accept',
    description: 'Accept a portal invite and create a viewer account linked to the client\'s organization.',
    auth: 'Public',
    section: 'Portal Invites',
    body: '{ token, full_name, email, password }',
    response: '{ success: true }',
  },

  // ─── 22. Settings ───
  {
    method: 'GET',
    path: '/api/settings/scheduling',
    description: 'Get scheduling settings (timezone, business hours, auto-schedule config).',
    auth: 'Required (admin)',
    section: 'Settings',
    response: 'Settings object',
  },
  {
    method: 'PATCH',
    path: '/api/settings/scheduling',
    description: 'Update scheduling settings.',
    auth: 'Required (admin)',
    section: 'Settings',
    body: 'Settings fields to update',
    response: 'Updated settings',
  },

  // ─── 23. Monday.com Integration ───
  {
    method: 'POST',
    path: '/api/monday/webhook',
    description: 'Receive Monday.com webhook events. Syncs client changes from Monday to vault.',
    auth: 'Public (webhook)',
    section: 'Monday.com Integration',
    response: '{ ok: true }',
  },
  {
    method: 'POST',
    path: '/api/monday/update',
    description: 'Push Cortex data back to Monday.com board columns.',
    auth: 'Required (admin)',
    section: 'Monday.com Integration',
    body: '{ item_id, updates: Record<columnId, value> }',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/monday/sync',
    description: 'Full sync: fetch all clients from Monday.com Clients board, upsert into Cortex DB and vault.',
    auth: 'Required (admin)',
    section: 'Monday.com Integration',
    response: '{ synced: number, errors?: string[] }',
  },

  // ─── 24. Todoist Integration ───
  {
    method: 'POST',
    path: '/api/todoist/connect',
    description: 'Connect a Todoist account with an API key. Validates the key before saving.',
    auth: 'Required (user)',
    section: 'Todoist Integration',
    body: '{ api_key: string, project_id?: string }',
    response: '{ connected: true }',
  },
  {
    method: 'POST',
    path: '/api/todoist/sync',
    description: 'Trigger a full Todoist <> Cortex sync (pull completed tasks + push new tasks).',
    auth: 'Required (user)',
    section: 'Todoist Integration',
    query: 'auto?: boolean (skips if synced recently)',
    response: '{ pulled: number, pushed: number, errors: string[] }',
  },

  // ─── 25. External API (v1) ───
  {
    method: 'GET',
    path: '/api/v1/clients',
    description: 'List all clients.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    response: '{ clients: [...] }',
  },
  {
    method: 'POST',
    path: '/api/v1/clients',
    description: 'Create a new client.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    body: 'Same as /api/clients/onboard schema',
    response: '{ client: object }',
  },
  {
    method: 'GET',
    path: '/api/v1/clients/[id]',
    description: 'Get a single client by ID.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    response: 'Client object',
  },
  {
    method: 'PATCH',
    path: '/api/v1/clients/[id]',
    description: 'Update a client.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    body: 'Client fields to update',
    response: 'Updated client object',
  },
  {
    method: 'GET',
    path: '/api/v1/clients/[id]/knowledge',
    description: 'List or full-text search a client\'s knowledge entries.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    query: 'type?, search?, include_links?, include_entities?',
    response: 'Array of knowledge entry objects',
  },
  {
    method: 'POST',
    path: '/api/v1/clients/[id]/knowledge',
    description: 'Create a knowledge entry.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    body: '{ type, title, content?, metadata?, source? }',
    response: '{ entry: KnowledgeEntry }',
  },
  {
    method: 'GET',
    path: '/api/v1/clients/[id]/knowledge/[entryId]',
    description: 'Get a single knowledge entry.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    response: 'Knowledge entry object',
  },
  {
    method: 'PATCH',
    path: '/api/v1/clients/[id]/knowledge/[entryId]',
    description: 'Update a knowledge entry.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    body: 'Knowledge entry fields to update',
    response: 'Updated entry',
  },
  {
    method: 'DELETE',
    path: '/api/v1/clients/[id]/knowledge/[entryId]',
    description: 'Delete a knowledge entry.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    response: '{ success: true }',
  },
  {
    method: 'POST',
    path: '/api/v1/clients/[id]/knowledge/search',
    description: 'Full-text search a client\'s knowledge entries.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    body: '{ query: string, type?, limit? }',
    response: '{ results: KnowledgeEntry[] }',
  },
  {
    method: 'GET',
    path: '/api/v1/clients/[id]/knowledge/import',
    description: 'Get import status for knowledge entries.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    response: 'Import status',
  },
  {
    method: 'POST',
    path: '/api/v1/clients/[id]/knowledge/import',
    description: 'Import knowledge entries in bulk.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    body: 'Array of knowledge entries',
    response: '{ imported: number }',
  },
  {
    method: 'GET',
    path: '/api/v1/clients/[id]/knowledge/graph',
    description: 'Get the knowledge graph for a client.',
    auth: 'API key (scope: clients)',
    section: 'External API (v1)',
    response: '{ nodes: Entity[], edges: Connection[] }',
  },
  {
    method: 'GET',
    path: '/api/v1/tasks',
    description: 'List tasks with filtering.',
    auth: 'API key (scope: tasks)',
    section: 'External API (v1)',
    query: 'client_id?, assignee_id?, status?, due_date_from?, due_date_to?',
    response: '{ tasks: [...] }',
  },
  {
    method: 'POST',
    path: '/api/v1/tasks',
    description: 'Create a task.',
    auth: 'API key (scope: tasks)',
    section: 'External API (v1)',
    body: '{ title, description?, status?, priority?, client_id?, assignee_id?, due_date?, task_type?, tags? }',
    response: '{ task: object }',
  },
  {
    method: 'GET',
    path: '/api/v1/tasks/[id]',
    description: 'Get a single task.',
    auth: 'API key (scope: tasks)',
    section: 'External API (v1)',
    response: 'Task object',
  },
  {
    method: 'PATCH',
    path: '/api/v1/tasks/[id]',
    description: 'Update a task.',
    auth: 'API key (scope: tasks)',
    section: 'External API (v1)',
    body: 'Task fields to update',
    response: 'Updated task',
  },
  {
    method: 'DELETE',
    path: '/api/v1/tasks/[id]',
    description: 'Delete a task.',
    auth: 'API key (scope: tasks)',
    section: 'External API (v1)',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/v1/shoots',
    description: 'List shoot events with filtering.',
    auth: 'API key (scope: shoots)',
    section: 'External API (v1)',
    query: 'client_id?, status?, date_from?, date_to?',
    response: '{ shoots: [...] }',
  },
  {
    method: 'GET',
    path: '/api/v1/shoots/[id]',
    description: 'Get a single shoot event.',
    auth: 'API key (scope: shoots)',
    section: 'External API (v1)',
    response: 'Shoot event object',
  },
  {
    method: 'GET',
    path: '/api/v1/posts',
    description: 'List scheduled posts for a client.',
    auth: 'API key (scope: scheduler)',
    section: 'External API (v1)',
    query: 'client_id: string (required), status?',
    response: '{ posts: [...] }',
  },
  {
    method: 'POST',
    path: '/api/v1/posts',
    description: 'Create a scheduled post.',
    auth: 'API key (scope: scheduler)',
    section: 'External API (v1)',
    body: '{ client_id, caption?, hashtags?, scheduled_at?, status?, platform_profile_ids?, media_ids? }',
    response: '{ post: object }',
  },
  {
    method: 'GET',
    path: '/api/v1/posts/[id]',
    description: 'Get a single post with platforms and media.',
    auth: 'API key (scope: scheduler)',
    section: 'External API (v1)',
    response: 'Post object',
  },
  {
    method: 'PATCH',
    path: '/api/v1/posts/[id]',
    description: 'Update a scheduled post.',
    auth: 'API key (scope: scheduler)',
    section: 'External API (v1)',
    body: 'Post fields to update',
    response: 'Updated post',
  },
  {
    method: 'DELETE',
    path: '/api/v1/posts/[id]',
    description: 'Delete a scheduled post.',
    auth: 'API key (scope: scheduler)',
    section: 'External API (v1)',
    response: '{ success: true }',
  },
  {
    method: 'GET',
    path: '/api/v1/team',
    description: 'List active team members.',
    auth: 'API key (scope: team)',
    section: 'External API (v1)',
    response: '{ team: [...] }',
  },
  {
    method: 'POST',
    path: '/api/v1/team',
    description: 'Create a team member.',
    auth: 'API key (scope: team)',
    section: 'External API (v1)',
    body: '{ full_name, email?, role? }',
    response: 'Team member object',
  },
  {
    method: 'POST',
    path: '/api/v1/search',
    description: 'Create a topic search record (returns ID, doesn\'t run the pipeline).',
    auth: 'API key (scope: search)',
    section: 'External API (v1)',
    body: '{ client_id, query, search_mode?: \'quick\'|\'deep\' }',
    response: '{ search: { id, query, status, search_mode, created_at } }',
  },
  {
    method: 'GET',
    path: '/api/v1/calendar/events',
    description: 'Fetch Google Calendar events for the API key owner\'s Nango connection.',
    auth: 'API key (scope: calendar)',
    section: 'External API (v1)',
    query: 'start: ISO8601, end: ISO8601',
    response: '{ events: CalendarEvent[] }',
  },
  {
    method: 'POST',
    path: '/api/v1/calendar/events',
    description: 'Create a Google Calendar event via Nango for the API key owner.',
    auth: 'API key (scope: calendar)',
    section: 'External API (v1)',
    body: '{ summary, description?, location?, start, end, attendees?: [{email}] }',
    response: '{ event: GoogleCalendarEvent }',
  },

  // ─── 26. Cron Jobs ───
  {
    method: 'POST',
    path: '/api/cron/sync-reporting',
    description: 'Sync social media analytics from Meta/Instagram for all active clients.',
    auth: 'Cron secret',
    section: 'Cron Jobs',
    response: '{ synced: number }',
  },
  {
    method: 'POST',
    path: '/api/cron/shoot-planner',
    description: 'Auto-generate AI shoot plans for shoots happening in 3 days.',
    auth: 'Cron secret',
    section: 'Cron Jobs',
    response: '{ planned: number }',
  },
  {
    method: 'POST',
    path: '/api/cron/publish-posts',
    description: 'Publish scheduled posts whose scheduled_at is now due.',
    auth: 'Cron secret',
    section: 'Cron Jobs',
    response: '{ published: number }',
  },
  {
    method: 'POST',
    path: '/api/cron/check-velocity',
    description: 'Check post velocity and send notifications about trending content.',
    auth: 'Cron secret',
    section: 'Cron Jobs',
    response: '{ checked: number }',
  },
  {
    method: 'POST',
    path: '/api/cron/sync-affiliates',
    description: 'Sync UpPromote affiliate data for all connected clients.',
    auth: 'Cron secret',
    section: 'Cron Jobs',
    response: '{ synced: number }',
  },
  {
    method: 'POST',
    path: '/api/cron/fyxer-import',
    description: 'Import meeting notes from Fyxer via Gmail polling + generate embeddings.',
    auth: 'Cron secret',
    section: 'Cron Jobs',
    response: '{ imported: number }',
  },
];
