-- Monthly deliverable slots: one row per expected deliverable per client per month.
-- Cron at 06:00 UTC on the 1st reads each active client's package_tier_allotments
-- and fans them out into N rows (e.g. 6 reels = slots 1..6 for deliverable_type
-- 'edited_video'). Editors then "Start project" on a pending row, which links
-- editing_projects.month_slot_id back here and flips status to in_progress.
-- Status finishes at 'delivered' once the share link is auto-minted/auto-sent
-- by the Mux webhook hook.

CREATE TABLE IF NOT EXISTS monthly_deliverable_slots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  month_start date NOT NULL,
  deliverable_type_id uuid NOT NULL REFERENCES deliverable_types(id) ON DELETE RESTRICT,
  slot_index int NOT NULL,
  editing_project_id uuid REFERENCES editing_projects(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'in_progress', 'delivered', 'skipped')),
  delivered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT monthly_deliverable_slots_month_first_day
    CHECK (extract(day from month_start) = 1),
  CONSTRAINT monthly_deliverable_slots_slot_index_positive
    CHECK (slot_index >= 1),
  UNIQUE (client_id, month_start, deliverable_type_id, slot_index)
);

CREATE INDEX IF NOT EXISTS monthly_deliverable_slots_client_month_idx
  ON monthly_deliverable_slots (client_id, month_start);

CREATE INDEX IF NOT EXISTS monthly_deliverable_slots_status_idx
  ON monthly_deliverable_slots (status)
  WHERE status IN ('pending', 'in_progress');

CREATE INDEX IF NOT EXISTS monthly_deliverable_slots_project_idx
  ON monthly_deliverable_slots (editing_project_id)
  WHERE editing_project_id IS NOT NULL;

ALTER TABLE editing_projects
  ADD COLUMN IF NOT EXISTS month_slot_id uuid
    REFERENCES monthly_deliverable_slots(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS editing_projects_month_slot_idx
  ON editing_projects (month_slot_id)
  WHERE month_slot_id IS NOT NULL;

-- updated_at trigger.
CREATE OR REPLACE FUNCTION monthly_deliverable_slots_set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS monthly_deliverable_slots_updated_at_trg
  ON monthly_deliverable_slots;
CREATE TRIGGER monthly_deliverable_slots_updated_at_trg
  BEFORE UPDATE ON monthly_deliverable_slots
  FOR EACH ROW
  EXECUTE FUNCTION monthly_deliverable_slots_set_updated_at();

-- RLS: admin-only writes; viewer reads scoped to their org via clients.organization_id.
-- Internal accounting surface in spirit, but the content-tools board target pills
-- read these counts so admins must SELECT.
ALTER TABLE monthly_deliverable_slots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS monthly_deliverable_slots_admin_all
  ON monthly_deliverable_slots;
CREATE POLICY monthly_deliverable_slots_admin_all
  ON monthly_deliverable_slots
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users u
      WHERE u.id = auth.uid()
        AND u.role IN ('admin', 'super_admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM users u
      WHERE u.id = auth.uid()
        AND u.role IN ('admin', 'super_admin')
    )
  );

COMMENT ON TABLE monthly_deliverable_slots IS
  'One row per expected deliverable per client per month. Generated by the 1st-of-month cron from package_tier_allotments; consumed by the content-tools board for target-vs-actual readouts. status: pending -> in_progress (editor starts) -> delivered (Mux webhook auto-mint) | skipped (admin override).';

COMMENT ON COLUMN editing_projects.month_slot_id IS
  'Links the editing project back to the monthly_deliverable_slot it was started from. Nullable for ad-hoc projects (clients without a package tier or one-off work).';
